import { linearTiming, TransitionSeries } from '@remotion/transitions';
import { fade } from '@remotion/transitions/fade';
import { AbsoluteFill, Html5Audio, interpolate, staticFile } from 'remotion';
import { AutoRevokeScene } from './scenes/AutoRevokeScene';
import { CtaScene } from './scenes/CtaScene';
import { HookScene } from './scenes/HookScene';
import { PremiumScene } from './scenes/PremiumScene';
import { PricingScene } from './scenes/PricingScene';
import { ProblemScene } from './scenes/ProblemScene';
import { TitleCardScene } from './scenes/TitleCardScene';

const TRANSITION_FRAMES = 8;

// Cold-open on the hook; the brand reveal lands as the payoff after the problem beat.
export const MAIN_SCENES = [
  { component: HookScene, durationInFrames: 120 },
  { component: ProblemScene, durationInFrames: 150 },
  { component: TitleCardScene, durationInFrames: 100 },
  { component: PremiumScene, durationInFrames: 270 },
  { component: AutoRevokeScene, durationInFrames: 330 },
  { component: PricingScene, durationInFrames: 210 },
  { component: CtaScene, durationInFrames: 140 },
] as const;

export const MAIN_DURATION_IN_FRAMES =
  MAIN_SCENES.reduce((total, scene) => total + scene.durationInFrames, 0) -
  (MAIN_SCENES.length - 1) * TRANSITION_FRAMES;

// The soundtracks are generated by the scripts/generate-soundtrack*.mjs scripts and already timed
// to the scene structure; the envelope here only handles the master fade-in/out.
const soundtrackVolume = (frame: number) =>
  interpolate(frame, [0, 20, MAIN_DURATION_IN_FRAMES - 60, MAIN_DURATION_IN_FRAMES], [0, 1, 1, 0], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });

// A type alias rather than an interface: Remotion's Composition props must satisfy
// Record<string, unknown>, which interfaces do not (no implicit index signature).
export type MainProps = {
  soundtrack: string;
};

export const Main = ({ soundtrack }: MainProps) => {
  return (
    <AbsoluteFill className="bg-black">
      <TransitionSeries>
        {MAIN_SCENES.flatMap((scene, index) => [
          ...(index > 0
            ? [
                <TransitionSeries.Transition
                  key={`transition-${scene.component.name}`}
                  presentation={fade()}
                  timing={linearTiming({ durationInFrames: TRANSITION_FRAMES })}
                />,
              ]
            : []),
          <TransitionSeries.Sequence key={`scene-${scene.component.name}`} durationInFrames={scene.durationInFrames}>
            <scene.component />
          </TransitionSeries.Sequence>,
        ])}
      </TransitionSeries>
      <Html5Audio src={staticFile(soundtrack)} volume={soundtrackVolume} />
    </AbsoluteFill>
  );
};
