name: Biome Format and linter check
on:
  push:
  pull_request:
    branches: [master]

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run Biome
        run: yarn lint
